version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: ${RABBITMQ_HOST}
    restart: always
    environment:
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
    ports:
      - '5672:5672'
      - '15672:15672'

  api:
    build: .
    ports:
      - '5659:5659'
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}

      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
    depends_on:
      - rabbitmq
    command: 'uvicorn main:app --host 0.0.0.0 --port 5659'

  task_worker:
    build: .
    restart: on-failure
    environment:
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
    depends_on:
      - rabbitmq
    command: 'python task_worker.py'


  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}


#  task_worker:
#    restart: on-failure
#    build: .
#    command: python task_worker.py
#    depends_on:
#      - rabbitmq
#      - postgres
#    environment:
#      RABBITMQ_HOST: ${RABBITMQ_HOST}



