version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ad
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgres/data


  people:
    image: request-api
    depends_on:
      - rabbitmq
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=admin
    ports:
      - "8000:8000"
    entrypoint: ["./entrypoint.sh"]
    command: [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5659" ]

volumes:
  postgres-data: